# Generated by Django 3.1.1 on 2020-11-24 07:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20201123_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newusers',
            name='mob',
        ),
        migrations.AddField(
            model_name='newusers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number should be of 10 digits', regex='^[0-9]+')]),
        ),
    ]
